### ISSUE TITLE
[question] LAPACK

### ISSUE THREAD

**Issue by dselivanov** [patperry/bench-term-matrix#4]
I noticed
> LAPACK: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib

How did you manage to force R to use Apple Accelerate LAPACK? For BLAS it is simple - just create symlink. But for LAPACK it is something different - I tried same trick, but R complains about LAPACK version...

**Comment by patperry** [comment]
Oh wow, I didn't realize that was the case. I installed R with hombrew: `brew install r` (followed by `brew cask install rstudio`)

**Comment by dselivanov** [comment]
Nice to know that "brewed" version comes with accelerated LAPACK! I will try.
